rainforest/config/routes.rb
Rainforest::Application.routes.draw do
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  get "users/new"
  get "users/create"
  resources :products
  resources :users, :only => [:new, :create]
  resources :sessions, :only => [:new, :create, :destroy]
end

rainforest/app/models/product.rb
class Product < ActiveRecord::Base

  has_many :reviews
  has_many :users, :through => :reviews

  # attr_accessible :description, :name, :price_in_cents - not required in rails 4.0

  validates :description, :name, :presence => true
  validates :price_in_cents, :numericality => {:only_integer => true}

  def price
    dollar_value = self.price_in_cents.to_f / 100
    "#{dollar_value.to_s(:currency)}"

  end


end

rainforest/app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :comment, :product_id
  belongs_to :user
  belongs_to :product
end

rainforest/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_presence_of :password, :on => :create
  has_many :reviews
  has_many :products, :through => :reviews
end

rainforest/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

rainforest/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json

  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

# GET /products/1
# GET /products/1.json

  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html #show.html.erb
      format.json { render json: @product }
    end 
  end

# GET /products/new
# GET /products/new.json

  def new
    @product = Product.new

    respond_to do |format|
      format.html #new.html.erb
      format.json { render json: @product }
    end 

  end

# GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

# POST /products
# POST /products.json

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }        
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }        
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end


# PUT /products/1
# PUT /products/1.json

  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }        
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
        format.html { redirect_to products_url }
        format.json { head :no_content }
    end
  end

  def product_params
    params.require(:product).permit(:name, :description, :price_in_cents)
  end

end

rainforest/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to products_url, :notice => "Logged in!"
    else
      flash.now[:alert] = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to products_url, :notice => "Logged out!"
  end
end

rainforest/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:email, :password, :password_confirmation))
    if @user.save
      redirect_to products_url, :notice => "Signed up!"
    else
      render "new"
    end
  end
end

rainforest/app/helpers/application_helper.rb
module ApplicationHelper
end

rainforest/app/helpers/products_helper.rb
module ProductsHelper
end

rainforest/app/helpers/sessions_helper.rb
module SessionsHelper
end

rainforest/app/helpers/users_helper.rb
module UsersHelper
end

rainforest/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Rainforest</title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<% if flash[:notice] %>
			<p id="notice"><%= flash[:notice] %></p>
		<% end %>

		<% if flash[:alert] %>
			<p id="alert"><%= flash[:alert] %></p>
		<% end %>

	<%= yield %>

		<p class="userinfo">
			<% if current_user %>
				Signed in as <%= current_user.email %>. <%= link_to "Log out", session_path("current"), :method => :delete %>
			<% else %>
				<%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
			<% end %>
		</p>
	</body>
</html>

rainforest/app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>


	<% if @product.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved: </h2>
				<ul>
					<%= @product.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
		</div>
	<% end %>



	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>

	<div class="field">
		<%= f.label :description %><br />
		<%= f.text_area :description%>
	</div>

	<div class="field">
		<%= f.label :price_in_cents %><br />
		<%= f.number_field :price_in_cents%>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

rainforest/app/views/products/edit.html.erb
<h2>Edit: <%= @product.name %> </h2>

<%= render 'form' %>
<%= link_to 'Back', products_path %>

rainforest/app/views/products/index.html.erb
<h1>Products#index</h1>
<p>Find me in app/views/products/index.html.erb</p>

<ul>

	<% @products.each do |p| %>

		<li>
			<%= link_to p.name, p  %>
		</li>


		<% end %>
</ul>

rainforest/app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>
<%= link_to 'Back', products_path %>

rainforest/app/views/products/show.html.erb
<h1>Products#show</h1>


<h2><%= @product.name %> <%= @product.price %> </h2>

<p><%= @product.description %></p>

rainforest/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

rainforest/app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
		<div class="error_messages">
			<h2> Form is invalid </h2>
			<ul>
				<% for message in @user.errors.full_messages %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :email %><br/>
		<%= f.text_field :email %>
	</div>

	<div class="field">
		<%= f.label :password %><br/>
		<%= f.password_field :password %>
	</div>

	<div class="field">
		<%= f.label :password_confirmation %><br/>
		<%= f.password_field :password_confirmation %>
	</div>

	<div class="actions"><%= f.submit %></div>

<% end %>